/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastrocliente;

import java.util.List;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.Debug.id;

/**
 *
 * @author jorge
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Busca
     */
    public Buscar() {
        initComponents();
        entBusca.setEnabled(false);
        saidaCodigo.setEnabled(false);
        saidaNome.setEnabled(false);
        saidaCPF.setEnabled(false);
        saidaTelefone.setEnabled(false);
        saidaLogradouro.setEnabled(false);
        saidaNumero.setEnabled(false);
        saidaBairro.setEnabled(false);
        saidaCidade.setEnabled(false);
        saidaEstado.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        opcaoBusca = new javax.swing.JComboBox<>();
        buscarDados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        saidaCodigo = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        saidaNome = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        saidaCPF = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        saidaTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        saidaLogradouro = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        saidaNumero = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        saidaBairro = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        saidaCidade = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        saidaEstado = new javax.swing.JFormattedTextField();
        btnSair = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        entBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Busca por Cliente");

        opcaoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opção de Busca", "CPF", "Nome", "Código" }));
        opcaoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcaoBuscaActionPerformed(evt);
            }
        });

        buscarDados.setText("Buscar");
        buscarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        saidaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome: ");

        saidaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF: ");

        try {
            saidaCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        saidaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaCPFActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        try {
            saidaTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        saidaTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaTelefoneActionPerformed(evt);
            }
        });

        jLabel6.setText("Logr.:");

        saidaLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaLogradouroActionPerformed(evt);
            }
        });

        jLabel7.setText("Nº:");

        try {
            saidaNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        saidaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaNumeroActionPerformed(evt);
            }
        });

        jLabel8.setText("Bairro:");

        saidaBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaBairroActionPerformed(evt);
            }
        });

        jLabel9.setText("Cidade:");

        saidaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaCidadeActionPerformed(evt);
            }
        });

        jLabel10.setText("Estado:");

        saidaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaEstadoActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opcaoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(entBusca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarDados))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saidaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saidaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saidaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saidaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(405, 405, 405)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saidaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(890, 890, 890))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btnExcluir)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnAlterar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnEditar)
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnLimpar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnSair))
                                        .addComponent(saidaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(saidaLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saidaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saidaBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saidaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opcaoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarDados)
                            .addComponent(entBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(saidaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saidaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saidaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saidaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saidaLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saidaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saidaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saidaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnLimpar)
                            .addComponent(btnExcluir)
                            .addComponent(btnAlterar)
                            .addComponent(btnEditar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcaoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcaoBuscaActionPerformed
        if (opcaoBusca.getSelectedItem() == "Nome"
                || opcaoBusca.getSelectedItem() == "CPF"
                || opcaoBusca.getSelectedItem() == "Código") {
            entBusca.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(jLabel1, "Selecione uma opção!");
        }
    }//GEN-LAST:event_opcaoBuscaActionPerformed

    private void saidaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaCodigoActionPerformed

    private void saidaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaNomeActionPerformed

    private void saidaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaCPFActionPerformed

    private void saidaTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaTelefoneActionPerformed

    private void saidaLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaLogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaLogradouroActionPerformed

    private void saidaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaNumeroActionPerformed

    private void saidaBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaBairroActionPerformed

    private void saidaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaCidadeActionPerformed

    private void saidaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaEstadoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        saidaBairro.setText("");
        saidaCPF.setText("");
        saidaCidade.setText("");
        saidaCodigo.setText("");
        saidaEstado.setText("");
        saidaLogradouro.setText("");
        saidaNome.setText("");
        saidaNumero.setText("");
        saidaTelefone.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void buscarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDadosActionPerformed

        UsuarioDAO dao = new UsuarioDAO();
        List<Usuario> users = dao.getUsuarios(this.entBusca.getText().toString());
        if (opcaoBusca.getSelectedItem() == "Nome" 
                || opcaoBusca.getSelectedItem() == "CPF"
                || opcaoBusca.getSelectedItem() == "Código") {

            for (int i = 0; i < users.size(); i++) {
                System.out.println(users.get(i).getNome());
                saidaCodigo.setText(users.get(i).getCodigo());
                saidaNome.setText(users.get(i).getNome());
                saidaCPF.setText(users.get(i).getCpf());
                saidaTelefone.setText(users.get(i).getTelefone());
                saidaLogradouro.setText(users.get(i).getLogradouro());
                saidaNumero.setText(users.get(i).getNumero());
                saidaBairro.setText(users.get(i).getBairro());
                saidaCidade.setText(users.get(i).getCidade());
                saidaEstado.setText(users.get(i).getEstado());

            }

        } else {
            JOptionPane.showMessageDialog(jLabel1, "Selecione uma opção!");
        }
    }//GEN-LAST:event_buscarDadosActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        
        entBusca.setEnabled(true);
        saidaCodigo.setEnabled(true);
        saidaNome.setEnabled(true);
        saidaCPF.setEnabled(true);
        saidaTelefone.setEnabled(true);
        saidaLogradouro.setEnabled(true);
        saidaNumero.setEnabled(true);
        saidaBairro.setEnabled(true);
        saidaCidade.setEnabled(true);
        saidaEstado.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Buscar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton buscarDados;
    private javax.swing.JTextField entBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> opcaoBusca;
    private javax.swing.JFormattedTextField saidaBairro;
    private javax.swing.JFormattedTextField saidaCPF;
    private javax.swing.JFormattedTextField saidaCidade;
    private javax.swing.JFormattedTextField saidaCodigo;
    private javax.swing.JFormattedTextField saidaEstado;
    private javax.swing.JFormattedTextField saidaLogradouro;
    private javax.swing.JFormattedTextField saidaNome;
    private javax.swing.JFormattedTextField saidaNumero;
    private javax.swing.JFormattedTextField saidaTelefone;
    // End of variables declaration//GEN-END:variables

    private void ativarCampos() {
        //Ativa os campos

        saidaCodigo.setEnabled(true);
        saidaNome.setEnabled(true);
        saidaCPF.setEnabled(true);
        saidaTelefone.setEnabled(true);
        saidaLogradouro.setEnabled(true);
        saidaNumero.setEnabled(true);
        saidaBairro.setEnabled(true);
        saidaCidade.setEnabled(true);
        saidaEstado.setEnabled(true);

    }

    private void retrieve() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
